# Generated by Django 6.0.4 on 2026-09-06

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_reorder_level_productvariant_reorder_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.FileField(upload_to="product-images/%Y/%m/", validators=[apps.core.validators.validate_image_upload]),
        ),
    ]
