# Generated by Django 6.0.4 on 2026-09-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_type", models.CharField(choices=[("return", "Return"), ("refund", "Refund")], max_length=16)),
                ("status", models.CharField(choices=[("requested", "Requested"), ("approved", "Approved"), ("rejected", "Rejected"), ("completed", "Completed")], default="requested", max_length=16)),
                ("reason", models.TextField(max_length=2000)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="requests", to="orders.order")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddIndex(
            model_name="orderrequest",
            index=models.Index(fields=["status", "request_type"], name="orders_orde_status_273e1a_idx"),
        ),
        migrations.AddConstraint(
            model_name="orderrequest",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "requested")), fields=("order", "request_type"), name="unique_open_order_request"),
        ),
    ]
