# Generated by Django 6.0.4 on 2026-09-06

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.FileField(blank=True, upload_to="profile-avatars/%Y/%m/", validators=[apps.core.validators.validate_image_upload]),
        ),
    ]
