# Generated by Django 6.0.4 on 2026-09-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cart_coupon"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_attempts",
                to="cart.cart",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=~models.Q(("external_payment_id", "")),
                fields=("provider", "external_payment_id"),
                name="unique_provider_external_payment",
            ),
        ),
    ]
