# Generated by Django 6.0.4 on 2026-09-06

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportticket",
            name="attachment",
            field=models.FileField(blank=True, upload_to="support-attachments/%Y/%m/", validators=[apps.core.validators.validate_support_upload]),
        ),
    ]
